<?php

use Illuminate\Database\Seeder;
use Faker\Factory;

class QuestionOptionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Asthma';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Angina/Chest Pain';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Anemia';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Arthritis';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Glaucoma';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Cancer';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Chronic bronchitis';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Cirrhosis';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Clotting disorder';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Diabetes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Emphysema';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Epilepsy';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Fractures';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Gallstones';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Heart attack';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Heart murmur';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Headaches';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Hepatitis';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='High Blood PRessure';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='High Cholesterol';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='HIV Positive/AIDS';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Kidney Disease';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Kidney Stones';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Migraines';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Positive TB Test';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Rheumatic Fever';
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Stroke';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Thrombophlebitis';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Thyroid Disease';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Tuberculosis';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Ulcers';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='8';
    	$option1->option_text='Other';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Bleeding Tendency';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Cancer';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Diabetes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Heart Attack';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Heart Disease';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='High Blood Pressure';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Kidney Disease';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Liver Disease';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Migraine Headaches';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Stones';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='9';
    	$option1->option_text='Tuberculosis';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='11';
    	$option1->option_text='Shortness of Breath';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='11';
    	$option1->option_text='Congestion';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='11';
    	$option1->option_text='Cough';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='11';
    	$option1->option_text='Short of Breath on Exertion';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='12';
    	$option1->option_text='Cold Intolerance';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='12';
    	$option1->option_text='Heat Intolerance';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='12';
    	$option1->option_text='Increased Thirst';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='13';
    	$option1->option_text='Abdominal pain';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='13';
    	$option1->option_text='Constipation';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='13';
    	$option1->option_text='Diarrhea';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='13';
    	$option1->option_text='Difficulty swallowing';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='13';
    	$option1->option_text='Heartburn';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='13';
    	$option1->option_text='Indigestion';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='13';
    	$option1->option_text='Nausea';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='14';
    	$option1->option_text='Blood in Urine';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='14';
    	$option1->option_text='Difficult or painful urination';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='14';
    	$option1->option_text='Frequent urination';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='15';
    	$option1->option_text='Dry Skin';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='15';
    	$option1->option_text='Flushing';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='15';
    	$option1->option_text='Rash';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='15';
    	$option1->option_text='Wound';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='16';
    	$option1->option_text='Chest Pain';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='16';
    	$option1->option_text='Fluttering Sensation';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='16';
    	$option1->option_text='Palpitations';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='16';
    	$option1->option_text='Sweating';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='16';
    	$option1->option_text='Swelling';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='16';
    	$option1->option_text='Varicose Veins';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='17';
    	$option1->option_text='Pregnant';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='17';
    	$option1->option_text='Menopause';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='18';
    	$option1->option_text='Difficulty With Erection';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='19';
    	$option1->option_text='Bleeding';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='19';
    	$option1->option_text='Easy Bruising';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='20';
    	$option1->option_text='Anxiety';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='20';
    	$option1->option_text='Depression';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='20';
    	$option1->option_text='High Stress';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='21';
    	$option1->option_text='Fatigue';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='21';
    	$option1->option_text='Fever';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='21';
    	$option1->option_text='Loss Of Appetite';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='21';
    	$option1->option_text='Weakness';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='21';
    	$option1->option_text='Weight gain';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='21';
    	$option1->option_text='Weight Loss';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='22';
    	$option1->option_text='Blurring of Vision';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='22';
    	$option1->option_text='Diminished Vision';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='22';
    	$option1->option_text='Loss of Vision';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='22';
    	$option1->option_text='Vision Floaters';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='23';
    	$option1->option_text='Difficulty Walking';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='23';
    	$option1->option_text='Dizziness';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='23';
    	$option1->option_text='Fainting';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='23';
    	$option1->option_text='Headaches';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='23';
    	$option1->option_text='Memory Loss';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='23';
    	$option1->option_text='Tingling';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='24';
    	$option1->option_text='Arm Pain';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='24';
    	$option1->option_text='Back Pain';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='24';
    	$option1->option_text='Joint Pain';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='24';
    	$option1->option_text='Leg Cramps';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='24';
    	$option1->option_text='Leg Pain';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='24';
    	$option1->option_text='Muscle Pain';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='25';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='25';
    	$option1->option_text='No';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='26';
    	$option1->option_text='0';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='26';
    	$option1->option_text='.5';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='26';
    	$option1->option_text='.5-1';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='26';
    	$option1->option_text='1-1.5';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='26';
    	$option1->option_text='1.5-2';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='26';
    	$option1->option_text='2-2.5';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='26';
    	$option1->option_text='3+';
    	$option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='<1 year';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='1 year';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='2 years';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='3 years';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='4 years';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='5 years';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='6-10 years';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='10-15 years';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='16-20 years';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='20-25 years';
        $option1->save();
        $option1=New App\QuestionOption();
        $option1->question_id='27';
        $option1->option_text='26-30 years';
        $option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='28';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='28';
    	$option1->option_text='No';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='<1 year';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='1 year';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='2 years';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='3 years';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='4 years';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='5 years';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='6-10 years';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='10-15 years';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='16-20 years';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='20-25 years';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='29';
    	$option1->option_text='26-30 years';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='30';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='30';
    	$option1->option_text='No';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='31';
    	$option1->option_text='1';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='31';
    	$option1->option_text='2';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='31';
    	$option1->option_text='3';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='31';
    	$option1->option_text='4';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='31';
    	$option1->option_text='5+';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='32';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='32';
    	$option1->option_text='No';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='33';
    	$option1->option_text='Never';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='33';
    	$option1->option_text='Once A Month';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='33';
    	$option1->option_text='2-4 Times A Month';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='33';
    	$option1->option_text='2-4 Times A Week';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='33';
    	$option1->option_text='4 Or More Times A Week';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='34';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='34';
    	$option1->option_text='No';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='35';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='35';
    	$option1->option_text='No';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='36';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='36';
    	$option1->option_text='No';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='37';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='37';
    	$option1->option_text='No';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='38';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='38';
    	$option1->option_text='No';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='39';
    	$option1->option_text='Yes';
    	$option1->save();
    	$option1=New App\QuestionOption();
    	$option1->question_id='39';
    	$option1->option_text='No';
    	$option1->save();

        factory(App\QuestionOption::class, 30)->create();
    }
}
